### ISSUE TITLE
Add this filter, to the Filterlists.com repo

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [nickspaargaren/pihole-google#13]
I’ve already done that to the past with the current filterlists I’ve made, and being surely the biggest and best place to find Filterlist, it might be pretty useful to suggest the different lists there.
They’ve even got a filter for different ad-blocking software, so we can stipulate those filterlists to be parsed for Pi-hole.
As I’m not the current owner of this repo obviously, I think they would prefer that you do it yourself.

**Comment by scoobydom0** [comment]
Well, I'm all for this. Add it @nickspaargaren !

**Comment by PoorPocketsMcNewHold** [comment]
https://github.com/collinbarrett/FilterLists/pull/892 Here we go. I´ve created a pull request for it.

**Comment by PoorPocketsMcNewHold** [comment]
And...We have been merged !
