### ISSUE TITLE
Add a license to this repo

### ISSUE THREAD

**Issue by ghost** [nickspaargaren/pihole-google#18]
Read this: https://help.github.com/en/articles/licensing-a-repository
HowTo: https://help.github.com/en/articles/adding-a-license-to-a-repository
Why?
"When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you."
From https://choosealicense.com/ :)

**Comment by nobodysu** [comment]
Second that.

**Comment by PoorPocketsMcNewHold** [comment]
Done. I’ve choose this Unlicense License entirely by myself, so this could potentially be changed in the future.
