### ISSUE TITLE
Please use Sublist3r. (Great job anyway!)

### ISSUE THREAD

**Issue by scoobydom0** [nickspaargaren/pihole-google#2]
It's an utility which shows as output all the subdomains that are related to a name. (trough various engines).
Example:
Input: google.com
Output:
...
google-proxy-66-249-93-92.google.com (this is not in pihole-google, yet
google-public-dns-a.google.com (this is not in pihole-google, yet)
goto.google.com (this is not in pihole-google, yet)
group.google.com (this is not in pihole-google, yet)
groups.google.com
...
[-] Total Unique Subdomains Found: 851

...and these are only a few examples! There is a lot of work to do and I'd love to contribute as much as I can. You can significantly improve the blocklist efficiency.
I'll do it for myself (but if I understand how Github works I have no problem to share my work here).
I appreciate very much the work with pihole-google blocklist you have done so far!

**Comment by nickspaargaren** [comment]
Thanks! I will definitely try Sublist3r as soon as possible! If you want you can create a pull request as well (that way we can merge our list).

**Comment by PoorPocketsMcNewHold** [comment]
That's indeed, quite great ! Not that much for the list I'm currently maintaining which is a phishing based, but still something pretty interesting to take note too. I'll close the issue as this suggestion as been acknowledged.
