### ISSUE TITLE
Wanting to contribute

### ISSUE THREAD

**Issue by payneusmc07** [nickspaargaren/pihole-google#28]
Hello;

I noticed you did not have a section for AWS blocking and asked for contributions in that area. I have a list of IPs which are associated with AWS tracking, but no direct URLS. Please let me know if this would be helpful.

**Comment by PoorPocketsMcNewHold** [comment]
Sorry for the little delay, Didn't notice you in my notifications.
As i've wished to expand the NO GAFAM block list, I'll sure be trying to expand to Amazon next, as it seems they're not a lot of Amazon anti-corp blocklist on the net.
I'll keep you updated once, No A is being done, your contribution will be extremely helpful.

**Comment by nickspaargaren** [comment]
Hi @payneusmc07 and @PoorPocketsMcNewHold ,

Sounds perfect to me, we can do a reverse IP lookup of these ip addresses, this could be very helpful.

I've created a new repository for it and invited you both, let's do this and maybe we can merge the two later into one GAFAM repository.

**Comment by nickspaargaren** [comment]
For the readers out there, the list is created and work-in-progress. Thank you. https://github.com/nickspaargaren/pihole-amazon
